Implement highlighting for script.inc and text.inc
SBird1337/poryscript-language pull request #21
Opened 2021-10-20 12:48 UTC by Jademalo

When using Poryscript, any section of asm included as `raw` will have really clear highlighting based on a combination of an arm grammar and the Poryscript language server.

However, when working with base pret repos, all existing maps will have their scripts in `scripts.inc` and `text.inc`. These do not highlight correctly when using the Poryscript grammar as it doesn't correctly overlay the arm grammar, and when using the arm grammar you don't get the benefits of the Poryscript language server.

I don't have a particularly good knowledge of TextMate grammars, and was unable to find a way to match content based on filename in a language.json so that if it was `scripts.inc` or `text.inc` it would designate the whole file as raw.  Because of this, I had to implement a secondary language that inherits the arm grammar for the whole file while also loading the language server. 

I don't know if there is a better approach than what I have implemented, but functionally it gives great results with clear syntax highlighting for the base pokemon scripts.

![image](https://user-images.githubusercontent.com/386846/138094048-215a473c-559b-4873-bb36-456f1d467d98.png)

I've also added an improvement to syntax in the `raw` blocks as well as for `scripts.inc` and `text.inc` that will highlight escapes for text strings. 

This seems to work fine in my testing, though I'd appreciate it being checked. I'm a bit out of my depth here, and this was all done by prodding at things. Names etc may not be ideal, and there might be a cleaner way than having to implement a whole second language.

2021-11-08 12:44 UTC, Jademalo commented
Any further thoughts on this? 
I've been using it for the last three weeks, and it's been working fantastically.

2021-12-29 15:20 UTC, SBird1337 commented
hey there, sorry I never really got back to it, I will have another look in the next few days and merge this PR!

2021-12-29 23:52 UTC, Jademalo commented
np, no rush!
Been using it since the original PR, and it's been working great. There's probably a better way of implementing what it does, but functionality wise having default `scripts.inc` and `text.inc` coloured is a godsend.

2021-12-30 01:48 UTC, SBird1337 requested changes
There's a few instances of inconsistant indentation, in fact there is even outside this PR, but it should be fixed regardless.

2021-12-30 01:48 UTC, SBird1337 commented on package.json
> +				],
tabs vs. spaces

2021-12-30 01:48 UTC, SBird1337 commented on package.json
> +			}
tabs vs. spaces

2022-01-05 16:43 UTC, Jademalo commented
Sorry about that taking a while, ended up extremely busy over the new year and didn't get a chance to do it.

2022-02-08 03:43 UTC, Jademalo commented
Hey, any updates on this?
All of the incorrect instances of tabs should be resolved now.

2022-02-11 18:16 UTC, merged